# Generated by Django 5.2.5 on 2025-09-09 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200)),
                ('bass_name', models.CharField(max_length=128)),
                ('no_strings', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12)])),
                ('blurb', models.TextField()),
                ('dateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
